name: Release and Publish to NPM
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: pnpm install
      - name: End message
        run: echo 'Done!'
